--- #YAML:1.0
name:                WWW-Mechanize-Shell
version:             0.48
abstract:            An interactive shell for WWW::Mechanize
license:             ~
author:              
    - Max Maischein <corion@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Hook::LexWrap:                 0.2
    HTML::Display:                 0
    HTML::TokeParser::Simple:      2
    LWP:                           5.69
    Term::Shell:                   0.02
    Test::Harness:                 2.3
    URI::URL:                      0
    WWW::Mechanize:                1.2
    WWW::Mechanize::FormFiller:    0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
